/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zybornit_loadlib_LoadLibrary */

#ifndef _Included_zybornit_loadlib_LoadLibrary
#define _Included_zybornit_loadlib_LoadLibrary

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     zybornit_loadlib_LoadLibrary
 * Method:    loadlib
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_zybornit_loadlib_LoadLibrary_loadlib
        (JNIEnv *, jobject, jstring);
JNIEXPORT void JNICALL Java_zybornit_loadlib_LoadLibrary_setJNIEnv(JNIEnv *env, jobject obj);
JNIEXPORT void JNICALL Java_zybornit_loadlib_LoadLibrary_releaseJNIEnv(JNIEnv *env, jobject obj);


#ifdef __cplusplus
}
#endif


#endif
